"""
Django settings for sistema_voto_ue_riobamba project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0drj0i+d)l6_40jeqi(k-$*o)4&q0=2z34v9@9@3u%e^y(u@^y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Aplicaciones.administracion',
    'Aplicaciones.elecciones',
    'Aplicaciones.padron',
    'Aplicaciones.votacion',
    'Aplicaciones.usuarios',
    'Aplicaciones.periodo',
    'Aplicaciones.autenticacion',
    'Aplicaciones.configuracion',
    'Aplicaciones.resultados',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_voto_ue_riobamba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Aplicaciones.configuracion.context_processors.logo_config',  # Añadir el context processor aquí
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_voto_ue_riobamba.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_votaciones_riobamba.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC PARA IMPORTAR ARCHIVOS CSS Y JS
STATIC_URL = '/static/'

# Ignorar archivos .map en desarrollo
STATICFILES_IGNORE_PATTERNS = [
    '*.map',
]
STATICFILES_DIRS = (os.path.join(BASE_DIR / 'sistema_voto_ue_riobamba/static'),)

#MEDIA PARA IMAGENES
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')

#MEDIA PARA IMAGENES

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'usuarios.Usuarios'  # Esto debe estar definido

#CORREO ELECTRONICO
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.aplicacionesutc.com'  
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Usa SSL en lugar de TLS si usas el puerto 465
EMAIL_USE_TLS = False  # TLS es para el puerto 587
EMAIL_HOST_USER = 'riobamba@aplicacionesutc.com'
EMAIL_HOST_PASSWORD = '&Ms&AFbeZf9L'  
DEFAULT_FROM_EMAIL = 'riobamba@aplicacionesutc.com'


#NUEVO CORREO ELECTRONICO




