# Generated by Django 5.1.5 on 2025-03-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_alter_padrónelectoral_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrónelectoral',
            name='usuario',
        ),
    ]
