# Generated by Django 5.1.5 on 2025-04-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0004_padrónelectoral_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrónelectoral',
            name='contraseña_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='padrónelectoral',
            name='usuario_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
