# Generated by Django 5.1.5 on 2025-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_roles_remove_usuario_rol_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
